### PR TITLE
Create French translation

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

I decided to keep the English name for this app, even in the French translation, because "App Launcher" makes sense in French too

### CODE REVIEW

**Comment by tibbi** [comment]
okay cool, just make sure to escape all quotes, else I will have to :p Thanks

**Comment by Poussinou** [comment]
Oops sorry I'll do it

**Comment by tibbi** [comment]
ye I did it together with the pull request. Seems like french people like using quotes.

**Comment by Poussinou** [comment]
Yes we like it. I'll not explain why here cause it's complicated, but we like it ;)

**Pull request merged**
