### PR TITLE
Fix compatibility with latest commons

### PR DESCRIPTION
**Pull request by julianfairfax**

### CODE REVIEW

**Comment by tibbi** [comment]
wtf

**Comment by julianfairfax** [comment]
... this change allows you to build Simple App Launcher with the latest version of Simple Commons. Otherwise it complains that Int is inferred but it was expecting Long

**Comment by tibbi** [comment]
and adding a fake license is the way to fix it? Really?

**Comment by julianfairfax** [comment]
> and adding a fake license is the way to fix it? Really?

I mean, yes? I didn't know how exactly you were going to do it, but this is what I found in other Simple Mobile Tools apps, and it actually builds this way.

**Comment by tibbi** [comment]
Just use 0L...

**Comment by julianfairfax** [comment]
That does work... sorry for my stupidity. I changed it in my branch but it seems this pull request didn't pick up on it. Nevermind about then.

**Pull request closed without merging**
