### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by vanitasvitae**
This PR contains individual commits per translated file, so that you can cherry pick desired translations. For example, I was not sure whether or not to translate the title, so if you don't want to have the title translated, just leave out that commit :)

### CODE REVIEW

**Comment by tibbi** [comment]
translate only this file please https://github.com/SimpleMobileTools/Simple-App-Launcher/blob/master/app/src/main/res/values-de/strings.xml , do not create any new files. Thanks

**Comment by vanitasvitae** [comment]
`short_description` and `full_description` are used by FDroid to provide localized descriptions. FDroid does not access `strings.xml`.

**Comment by tibbi** [comment]
well okay, accepting it wont break anything. But those files arent used by any other app.

**Comment by vanitasvitae** [comment]
> But those files arent used by any other app.

You mean any other of your apps? There are quite a bunch of apps on FDroid that make use of localized fastlane metadata.

**Comment by tibbi** [comment]
I mean apps from SimpleMobileTools suite. I update the app descriptions only on Google Play manually by copypasting strings.xml values. That is the easiest way of translating them to people.

**Comment by vanitasvitae** [comment]
Ah got you.

**Comment by vanitasvitae** [comment]
Btw: If you keep the description strings in strings.xml, you may want to use a script or something to copy the respective resources to the fastlane directory to have FDroid pick up the translations :)

**Comment by tibbi** [comment]
maybe in the future, for now I didnt really want to optimize anything for fdroid. I created the whole fastlane folder only to have a place for the screenshots, it is not tied to my Google Play account in any way.

**Pull request merged**
